//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YamaletdinovMasterPolEntities : DbContext
    {
        public YamaletdinovMasterPolEntities()
            : base("name=YamaletdinovMasterPolEntities")
        {
        }
        private static YamaletdinovMasterPolEntities _context;

        public static YamaletdinovMasterPolEntities GetContext()
        {
            if (_context == null)
                _context = new YamaletdinovMasterPolEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Delivers> Delivers { get; set; }
        public virtual DbSet<DeliversType> DeliversType { get; set; }
        public virtual DbSet<MaterialCountChangeHistory> MaterialCountChangeHistory { get; set; }
        public virtual DbSet<MaterialDeliveryHistory> MaterialDeliveryHistory { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<MaterialType> MaterialType { get; set; }
        public virtual DbSet<Partners> Partners { get; set; }
        public virtual DbSet<PartnerType> PartnerType { get; set; }
        public virtual DbSet<ProductMaterial> ProductMaterial { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductSale> ProductSale { get; set; }
        public virtual DbSet<ProductTypes> ProductTypes { get; set; }
        public virtual DbSet<ShopPartner> ShopPartner { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<StaffPartners> StaffPartners { get; set; }
    }
}
