//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partners()
        {
            this.ShopPartner = new HashSet<ShopPartner>();
            this.StaffPartners = new HashSet<StaffPartners>();
        }
    
        public int ID { get; set; }
        public int PartnerType { get; set; }
        public string PartnerName { get; set; }
        public string DirectorFirstName { get; set; }
        public string DirectorName { get; set; }
        public string DirectorPatronomyc { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string JuridicalIndex { get; set; }
        public string JuridicalState { get; set; }
        public string JuridicalCity { get; set; }
        public string JuridicalStreet { get; set; }
        public int JuridicalHome { get; set; }
        public string INN { get; set; }
        public int Rate { get; set; }
        public string Logo { get; set; }
    
        public virtual PartnerType PartnerType1 { get; set; }
        public virtual ProductSale ProductSale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopPartner> ShopPartner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffPartners> StaffPartners { get; set; }

        public string typename
        {
            get
            {
                return PartnerType1.TypeName;
            }
        }
        public int PartnerTypePlusOne
        {
            get
            {
                return PartnerType - 1;
            }
            set
            {
                PartnerType = value;
            }
        }

        public int Discount
        {
            get
            {
                if (ProductSale.Count < 10000)
                    return 0;
                else if (ProductSale.Count >= 10000 && ProductSale.Count < 50000)
                    return 5;
                else if (ProductSale.Count >= 50000 && ProductSale.Count < 300000)
                    return 10;
                else
                    return 15;
            }
        }
        public string PhoneFiltr
        {
            get
            {
                return Phone.Replace("+", "").Replace("-", "").Replace("(", "").Replace(")", "").Replace(" ", "");
            }
        }
    }
}
