//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.ProductMaterial = new HashSet<ProductMaterial>();
            this.ProductSale = new HashSet<ProductSale>();
        }
    
        public int ID { get; set; }
        public int TypeProd { get; set; }
        public string Name { get; set; }
        public string Article { get; set; }
        public decimal MinCostForPartner { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<int> PackageSizeWidth { get; set; }
        public Nullable<int> PackageSizeHight { get; set; }
        public Nullable<int> PackageSizeLength { get; set; }
        public Nullable<int> WeightWithoutPackage { get; set; }
        public Nullable<int> WeightWithPackage { get; set; }
        public string QualityImage { get; set; }
        public string StandartNum { get; set; }
        public Nullable<int> CreateTime { get; set; }
        public Nullable<int> NumDepartment { get; set; }
        public Nullable<int> CountPeopleInFabric { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMaterial> ProductMaterial { get; set; }
        public virtual ProductTypes ProductTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSale> ProductSale { get; set; }

        

    }
}
