//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopPartner
    {
        public int ShopID { get; set; }
        public int PartnerID { get; set; }
        public string ShopPlace { get; set; }
    
        public virtual Partners Partners { get; set; }
    }
}
