//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffPartners
    {
        public int ID_StaffPartners { get; set; }
        public int ID_Staff { get; set; }
        public int ID_Partners { get; set; }
    
        public virtual Partners Partners { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
