//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.StaffPartners = new HashSet<StaffPartners>();
        }
    
        public int StaffID { get; set; }
        public string FirstName { get; set; }
        public string Name { get; set; }
        public string Patronomyc { get; set; }
        public System.DateTime BirthDay { get; set; }
        public int PassportNum { get; set; }
        public string PassportOrgCode { get; set; }
        public string PassportGiveOrg { get; set; }
        public Nullable<System.DateTime> PassportGiveDate { get; set; }
        public int PassportSer { get; set; }
        public string BankData { get; set; }
        public string FamilyStatus { get; set; }
        public string HealthStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffPartners> StaffPartners { get; set; }
    }
}
